name: Iceaxe-Testing-CI

on: [push, pull_request, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHA_PAT }}

      - name: Assemble
        run: |
          ./gradlew -i iceaxe-dbtest:showTsubakuroManifest clean assemble

      - name: Check
        run: |
          ./gradlew -i check -x :iceaxe-dbtest:test

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
        with:
          spotbugs_input: '**/build/reports/spotbugs/main/*.xml'
          checkstyle_input: '**/build/reports/checkstyle/main.xml'
